apiVersion: 1

deleteDatasources:
  - name: Zabbix PostgreSQL
    orgId: 1

datasources:
  - name: Zabbix PostgreSQL
    uid: zabbix-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: $POSTGRES_USER
    isDefault: false
    editable: false
    jsonData:
      database: $POSTGRES_DB
      sslmode: disable
      postgresVersion: 1600
    secureJsonData:
      password: $POSTGRES_PASSWORD
